name = "portfoliov2"
compatibility_date = "2023-10-30"

[build]
command = "npm run build"

[site]
bucket = ".vercel/output/static"

[build.upload]
format = "service-worker"

[env.production]
workers_dev = true

[env.staging]
workers_dev = true

[[rules]]
type = "NavigationRoute"
route = "/*"
