name = "your-project-name"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".vercel/output/static"

pages_build_output_dir = ".vercel/output/static"
